services:
    agm_dev_app:
        build:
            context: .
            dockerfile: docker/dev/Dockerfile
        container_name: agm_dev_app
        restart: on-failure:5
        working_dir: /var/www/agm
        volumes:
            - .:/var/www/agm
            - ./docker/dev/supervisor/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
        depends_on:
            - agm_dev_mysql
            - agm_dev_redis
            - agm_dev_node
            - agm_dev_soketi
        networks:
            - agm_dev

    agm_dev_nginx:
        image: nginx:latest
        container_name: agm_dev_nginx
        restart: on-failure:5
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/agm
            - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - agm_dev_app
        networks:
            - agm_dev

    agm_dev_mysql:
        image: mysql:8.0
        container_name: agm_dev_mysql
        restart: on-failure:5
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - agm_dev_mysql_data:/var/lib/mysql
        networks:
            - agm_dev

    agm_dev_redis:
        image: redis:latest
        container_name: agm_dev_redis
        restart: on-failure:5
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - "6380:6379"
        networks:
            - agm_dev

    agm_dev_node:
        image: node:20
        container_name: agm_dev_node
        restart: on-failure:5
        working_dir: /var/www/agm
        volumes:
            - .:/var/www/agm
        ports:
            - "5175:5173"
        networks:
            - agm_dev
        stdin_open: true
        tty: true

    agm_dev_soketi:
        image: quay.io/soketi/soketi:latest
        container_name: agm_dev_soketi
        restart: on-failure:5
        ports:
            - "6002:6002"
            - "9602:9601" # Optional metrics port
        environment:
            SOKETI_DEBUG: "true"
            SOKETI_METRICS_SERVER_PORT: "9602"
            SOKETI_DEFAULT_APP_ID: "${PUSHER_APP_ID}"
            SOKETI_DEFAULT_APP_KEY: "${PUSHER_APP_KEY}"
            SOKETI_DEFAULT_APP_SECRET: "${PUSHER_APP_SECRET}"
            SOKETI_PORT: 6002
        networks:
            - agm_dev

volumes:
    agm_dev_mysql_data:

networks:
    agm_dev:
