services:
    agm_prod_app:
        build:
            context: .
            dockerfile: docker/prod/Dockerfile
        container_name: agm_prod_app
        restart: on-failure:5
        working_dir: /var/www/agm
        volumes:
            - .:/var/www/agm
            - ./docker/prod/supervisor/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
        depends_on:
            - agm_prod_mysql
            - agm_prod_redis
            - agm_prod_node
            - agm_prod_soketi
        networks:
            - agm_prod

    agm_prod_nginx:
        image: nginx:stable
        container_name: agm_prod_nginx
        restart: on-failure:5
        ports:
            - "80:80"
        volumes:
            - .:/var/www/agm
            - ./docker/prod/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - agm_prod_app
        networks:
            - agm_prod

    agm_prod_mysql:
        image: mysql:8.0
        container_name: agm_prod_mysql
        restart: on-failure:5
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - agm_prod_mysql_data:/var/lib/mysql
        networks:
            - agm_prod

    agm_prod_redis:
        image: redis:latest
        container_name: agm_prod_redis
        restart: on-failure:5
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - "6379:6379"
        networks:
            - agm_prod

    agm_prod_node:
        image: node:20
        container_name: agm_prod_node
        restart: on-failure:5
        working_dir: /var/www/agm
        volumes:
            - .:/var/www/agm
        ports:
            - "5173:5173"
        networks:
            - agm_prod
        stdin_open: true
        tty: true

    agm_prod_soketi:
        image: quay.io/soketi/soketi:latest
        container_name: agm_prod_soketi
        restart: on-failure:5
        ports:
            - "6001:6001"
            - "9601:9601" # Optional metrics port
        environment:
            SOKETI_DEBUG: "true"
            SOKETI_METRICS_SERVER_PORT: "9601"
            SOKETI_DEFAULT_APP_ID: "${PUSHER_APP_ID}"
            SOKETI_DEFAULT_APP_KEY: "${PUSHER_APP_KEY}"
            SOKETI_DEFAULT_APP_SECRET: "${PUSHER_APP_SECRET}"
        networks:
            - agm_prod

volumes:
    agm_prod_mysql_data:

networks:
    agm_prod:
